### PR TITLE
fix #3 #6

### LINKED ISSUE #3: get a trouble with 'class Tes{' if it is no blank
it is a unreadable code with follow:
```
class Tes{  //<-- Need a blank
...
}
```
a good way is like this.
```
class Tes {
...
}
```

### PR DESCRIPTION
**Pull request by huang12zheng**
ChangeLog:

fix bug unreadable code in sample `class XX{`

add dart_data_class_generator.fromMap.enabled
remove dart_data_class_generator.fromMap
add dart_data_class_generator.constructor.enabled
remove dart_data_class_generator.constructor
add dart_data_class_generator.hashCode.enabled
remove dart_data_class_generator.hashCode

### CODE REVIEW

**Comment by BendixMa** [comment]
Please see if my latest commit fixes your issues as I've added some new functionality that now fully supports equatable. You can test it by setting the `useEquatable` setting to true.

**Comment by BendixMa** [comment]
For example running the generator on this class

```dart
class Test {
  final String a;
}
```

would generate this:

```dart
import 'dart:convert';

import 'package:equatable/equatable.dart';

class Test with EquatableMixin {
  final String a;
  Test({
    this.a = '',
  });

  Test copyWith({
    String a,
  }) {
    return Test(
      a: a ?? this.a,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'a': a,
    };
  }

  static Test fromMap(Map<String, dynamic> map) {
    if (map == null) return null;
  
    return Test(
      a: map['a'] ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  static Test fromJson(String source) => fromMap(json.decode(source));

  @override
  String toString() => 'Test a: $a';

  @override
  List<Object> get props => [a];
}
```

**Comment by BendixMa** [comment]
I renamed all the settings that are related to code generation as you proposed to end with `.enabled` as I agree that this is more expressive. I incorporated most of the changes now onto the master branch which is why I close this PR and I can publish it in the coming days to the vscode marketplace if there are no further suggestions from your side.

**Comment by huang12zheng** [comment]
some problem:
1. 
```
UserSetting:  Dart_data_class_generator: Equality
If true, generates a value equality function for a data class.
```
is trouble with reminding.Since We have a Setting EquableMixin

 it is need to add a remark like  `it is override operator ==`

2. I use ToolClaass #4 
```dart
abstract class ModelBase with EquatableMixin{u
  Map<String, Object> toMap();
  String toJson() => json.encode(toMap());
  copyWith();
  String toString() => '$runtimeType ${toJson()}';
}
```
it is not adaptive to you code

**Pull request closed without merging**
